name: Rotate logo (every 10 minutes)

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rotate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync with remote and select logo
        id: picker
        run: |
          set -euo pipefail
          
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git fetch origin main
          git checkout main
          git reset --hard origin/main
          
          mkdir -p docs
          if [ ! -d images ] || [ -z "$(ls -A images 2>/dev/null)" ]; then
            echo "ERROR: images/ directory is empty or missing"; exit 1
          fi
          mapfile -t imgs < <(ls -1 images | sort)
          count=${#imgs[@]}
          if [ $count -eq 0 ]; then
            echo "No images found"; exit 1
          fi
          slot=$(( $(date +%s) / (10*60) ))
          idx=$(( slot % count ))
          selected="images/${imgs[$idx]}"
          cp -- "$selected" docs/logo.png
          echo "selected_file=$(basename "$selected")" >> $GITHUB_OUTPUT
          
          git add docs/logo.png

      - name: Commit and push if changed
        env:
          SELECTED_FILE: ${{ steps.picker.outputs.selected_file }}
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          if git diff --cached --quiet; then
            echo "No changes detected. Logo is the same."
            exit 0
          fi
          
          git commit -m "Rotate logo: ${SELECTED_FILE}"
          git push origin main
